---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 杨以鑫.
--- DateTime: 2021/3/22 19:43
---

--[[
    多行注释
--]]

-- 标识符：字母，下划线，数字组成，数字不能开头，不能使用特殊字符

-- 关键字:
-- and break do else elseif end false for function if
-- in local nil not or repeat return then true until while

-- 不推荐使用下划线 + 大写字母(_Age)

-- 推荐命名规则：
-- 常量用全大写和下划线：MY_ACOUNT
-- 变量第一个字母小写： strNumber
-- 全局变量第一个字母用小写 g 表示 gMyAcount
-- 函数名第一个字母大写 function MyFirstFunction()

-- 变量
-- 变量属于弱类型，不需要声明，不需要声明类型，类型可改变
-- print() 是 lua 中内置的方法
str1 = nil; -- 销毁 str1 所占用的资源

-- 五种基本变量类型：nil, boolean, string, number, table
print(type(a));
print(type(true));
print(type("str"));
print(type(5));
print(type({1,2,3}));









