---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 杨以鑫.
--- DateTime: 2021/3/22 21:32
---

-- 定义多行字符串
strMultiLine = [[
    <html>
        <head></head>
        <body>
            <a href = "http://www.baidu.com">baidu</a>
        </body>
    </html>
]]

-- 字符串连接
str = "123";
print("输出变量 str = " .. str);

-- 字符串的转换
print("2.2" + "30");                        -- C# 中输出内容："2.230"
print("2.2" + 30);

-- 求字符串的长度
print(#"中文字符串");                        -- 输出：15

-- 字符串与其他类型的转换
-- tonumber(), tostring()
numArray  ={12, 15, 80};
print("表的内容：" .. tostring(numArray));   -- 必须使用 tostring() 场合
num = nil
print("num = " .. tostring(num));           -- 必须使用 tostring() 场合

--[[
数据类型
    nil         空数据
    boolean
    string
    number      小数类型
    table       表示一个集合，序号从1开始
    function
    userdata
    thread
--]]
function fun1()
    return 10;
end

